#3 Add CODE_OF_CONDUCT.md and CONTRIBUTING.md
GenomicDataInfrastructure/gdi-userportal-docs pull request #15
Opened 2023-12-08 20:49 UTC by brunopacheco1

2023-12-11 08:19 UTC, admy7 commented on CONTRIBUTING.md
> +- To see if other users have experienced (and potentially already solved) the same issue you are having, check if there is not already a bug report existing for your bug or error in the [bug tracker]
This link https://github.com/GenomicDataInfrastructure/gdi-userportal-docsissues?q=label%3Abug is not working (404)

2023-12-11 11:40 UTC, hallundbaek commented on CODE_OF_CONDUCT.md
I reckon we should use the https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md instead of the one generated by generator.contributing.md that just sums it up?

2023-12-11 12:47 UTC, hallundbaek requested changes

2023-12-11 12:47 UTC, hallundbaek commented on CONTRIBUTING.md
> +## Join The Project Team
drop section

2023-12-25 23:58 UTC, brunopacheco1 commented on CONTRIBUTING.md
> +### Improving The Documentation
Fixed.

2023-12-25 23:58 UTC, brunopacheco1 commented on CONTRIBUTING.md
> +### Commit Messages
Removed.

2023-12-25 23:58 UTC, brunopacheco1 commented on CONTRIBUTING.md
> +## Join The Project Team
Removed.

2023-12-25 23:58 UTC, brunopacheco1 commented on CONTRIBUTING.md
> +### Your First Code Contribution
Removed.

2023-12-26 00:00 UTC, brunopacheco1 commented on CONTRIBUTING.md
> +### Suggesting Enhancements
Fixed.

2023-12-26 00:02 UTC, brunopacheco1 commented on CONTRIBUTING.md
> +### Reporting Bugs
Removed.

2023-12-26 00:03 UTC, brunopacheco1 commented on CONTRIBUTING.md
> +## Styleguides
Nope.

2023-12-26 00:03 UTC, merged