add tutorial for running harvester for fair data points
GenomicDataInfrastructure/gdi-userportal-docs pull request #23
Opened 2023-12-20 21:41 UTC by admy7

Add tutorial for running harvester for fair data points

2023-12-20 22:12 UTC, brunopacheco1 requested changes

2023-12-20 22:12 UTC, brunopacheco1 commented on content/harvester/_index.md
> +# Testing CKAN harvesting of FAIR data points?
Please confirm with a different file, but I believe you are missing the title metadata.

2023-12-20 22:12 UTC, brunopacheco1 commented on content/harvester/_index.md
> +We assume that CKAN is properly set up (as documented in this wiki) and running.
`We assume that CKAN is properly set up and running, as documented in this wiki.` What do you think?

2023-12-20 22:12 UTC, brunopacheco1 commented on content/harvester/_index.md
> +- Configuration: { "profile": "fairdatapoint_dcat_ap" }
This json content could be inside an inline code block, like this `{ "profile": "fairdatapoint_dcat_ap" }`.

2023-12-21 08:27 UTC, hcvdwerf approved these changes

2023-12-21 12:57 UTC, brunopacheco1 approved these changes

2023-12-21 12:58 UTC, merged